export default {
    DEFAULT_BG: require('../assets/images/default_bg.png'),
    HOME_ICON: require('../assets/images/home_icon.png'),
    MARKET_ICON: require('../assets/images/market_icon.png'),
    SWAP_ICON: require('../assets/images/swap_icon.png'),
    WALLET_ICON: require('../assets/images/wallet_icon.png'),
    PROFILE_ICON: require('../assets/images/profile_icon.png'),
    BELL_ICON: require('../assets/images/bell_icon.png'),
    USER: require('../assets/images/user.png'),
    DROPDOWN_ICON: require('../assets/images/dropdown.png'),
    UP_ICON: require('../assets/images/up_icon.png'),
    SEND_ICON: require('../assets/images/send_icon.png'),
    RECEIVE_ICON: require('../assets/images/receive_icon.png'),
    ADD_ICON: require('../assets/images/add_icon.png'),
    BITCOIN_ICON: require('../assets/images/bitcoin_icon.png'),
    SOLANA_ICON: require('../assets/images/solana_icon.png'),
    ETH_ICON: require('../assets/images/eth_icon.png'),
    NFT_1: require('../assets/images/nft_1.png'),
    NFT_2: require('../assets/images/nft_2.png'),
    NFT_3: require('../assets/images/nft_3.png'),
    ETH: require('../assets/images/eth_small.png'),
    CARD_1: require('../assets/images/card_1.png'),
    CARD_2: require('../assets/images/card_2.png'),
    CARD_3: require('../assets/images/card_3.png'),
    CARD_4: require('../assets/images/card_4.png'),
    CARD_5: require('../assets/images/card_5.png'),
    HEART_ICON: require('../assets/images/heart.png')
}